### ISSUE TITLE
"next" button simply reloads page

### ISSUE THREAD

**Issue by adamwong246** [forwarder/meteor-wizard#22]
Firstly, I'm using an older version of meteor-wizard due to version constraints, so rather than `wizardButtons`, I'm using the template `__wizard_nav`.
Secondly,, I'm trying to use custom templates in a way that does not force me to manually insert the document. In other words, I'm actively trying to avoid using the `onSubmit` hook and prefer to rely on autoforms own methods.

```
template(name="offeringDetails")
  +autoForm(id="offering-details" doc=step.data schema=step.schema)
    +afQuickField(name='title')
    +afQuickField(name='summary')
    +afQuickField(name='description')
    +afQuickField(name="picture")
    +afQuickField(name='video')
    +afQuickField(name='corporateEntity')
    +afQuickField(name='prospectus')
    
    +__wizard_nav


template(name="offeringContract")
  +autoForm(id="offering-contract" doc=step.data schema=step.schema)
    +afQuickField(name='totalValuation')
    +afQuickField(name='threshold')
    +afQuickField(name='returnCap')
    +afQuickField(name='percentRevenueShared')
    +afQuickField(name='sharePrice')
    +afQuickField(name='sharesIssued')
    +afQuickField(name='sharesOffered')
    
    +__wizard_nav
    
    button.btn.btn-primary(type="submit") Create offering

    
template(name='newOffering')
  .container
    h2 Create an Offering
    +wizard(id="basic-wizard" steps=steps)
```
```
Template.newOffering.helpers
  steps: ->
    [
      {
       id: 'offering-details'
       title: 'Details'
       template: 'offeringDetails'
       schema: Schemas.OfferingDetails
      },
      {
       id: 'offering-contract'
       title: 'Contract'
       template: 'offeringContract'
       schema: Schemas.OfferingContract
      }
    ]
```
```
@Schemas.OfferingDetails = new SimpleSchema
 title:
   type: String
   max: 60
 description:
   type: String
   autoform:
     type: 'markdown'
 corporateEntity:
   type: String
   optional: true
   max: 144
 summary:
   type: String
   max: 144
 video:
   type: String
   optional: true
   autoform:
    placeholder: 'https://www.youtube.com/embed/NUN_bmiVmXo'
 picture:
   type: String
   optional: true
   autoform:
     afFieldInput:
       type: 'fileUpload'
       collection: 'offering_images'
   label: 'Offering Image'
 prospectus:
   type: String
   optional: true
   autoform:
     afFieldInput:
       type: 'fileUpload'
       collection: 'prospectuses'
   label: 'Prospectus'

@Schemas.OfferingContract = new SimpleSchema
  totalValuation:
    type: Number
    label: "How much money would you like to raise?"
    defaultValue: 100000
    min: 100
    autoform:
      type: 'usdCents'
  threshold:
    type: Number
    label: "Is there a minimum amount that is required to fulfill the Contract?"
    defaultValue: 0
    min: 0
    autoform:
      type: 'usdCents'
  returnCap:
    type: Number
    label: "Revenue sharing return cap. Past which, shareholders are no longer entitled to receive revenue share"
    defaultValue: 2
    min: 1
  percentRevenueShared:
    type: Number
    label: "The percent of gross revenue will be applied each period to pay back investors"
    defaultValue: 50
    min: 1
  sharePrice:
    type: Number
    label: "Minimum investment required per person (share price)"
    defaultValue: 1000
    min: 100
    autoform:
      type: 'usdCents'
  sharesIssued:
    type: Number
    label: "Total number of shares that will be created"
    min: 1
    autoValue: ->
      if @isInsert
        parseInt(parseInt(@siblingField('totalValuation').value) / parseInt(@siblingField('sharePrice').value))
        #automatic field user shouldn't enter directly
  sharesOffered:
    type: Number
    label: "Number of shares to be made available for investor purchase"
    min: 1
    autoValue: ->
      if @isInsert
        sharesToIssue = parseInt(parseInt(@siblingField('totalValuation').value) / parseInt(@siblingField('sharePrice').value))
        parseInt(sharesToIssue * parseInt(@siblingField('percentRevenueShared').value) / 100)
        #automatic field user shouldn't enter directly

@Schemas.Offering = new SimpleSchema
  contract:
    type: @Schemas.OfferingContract
  details:
    type: @Schemas.OfferingDetails
```
